Fix dependencies to allow builds in 2023
facebookincubator/xar pull request #55
Opened 2023-12-27 04:42 UTC by ekacnet

Right out of the box `cargo build` don't work for `clean_xar_mounts` in 2023.
It turns out that something is wrong with the 2.1.x version of slog, I didn't look very hard to know what. It seems that upgrading to something a bit newer is working.
Similarly using 1.0 version of anyhow is not working (complains about missing backtrace) instead using a recent version and enabling the `backtrace` feature is solving the problem

2023-12-27 19:45 UTC, itamaro requested changes
I suggested changes to match the versions we build with internally - please let me know if this works for the open-source build

2023-12-27 19:45 UTC, itamaro commented on xar/clean_xar_mounts/Cargo.toml
> +anyhow = { version = "1.0.52", features = ["backtrace"] }
```suggestion
anyhow = { version = "1.0.75", features = ["backtrace"] }
```

2023-12-27 19:45 UTC, itamaro commented on xar/clean_xar_mounts/Cargo.toml
> +slog = "2.3.0"
```suggestion
slog = "2.7.*"
```

2023-12-28 03:15 UTC, ekacnet commented
Yes @itamaro  it's working I build it locally.

2023-12-28 22:35 UTC, closed without merging